### ISSUE TITLE
Common js: certain dependencies not registering

### ISSUE THREAD

**Issue by tnrich** [auchenberg/dependo#24]
Hey there, 

I've got an app I'd like to see the dependency tree for. The 'entry point' file is named App.js and the top of App.js looks like: 

```
var React = require('react');
var Router = require('react-router'); // or var Router = ReactRouter; in browsers
var Route = Router.Route;
var RouteHandler = Router.RouteHandler;
var Link = Router.Link;

var Dashboard = require('./Dashboard.js');
var SequenceEditor = require('./SequenceEditor.js');
var Skeleton = require('./Skeleton.js');
etc.
```

Unfortunately, none of the dependencies are showing up for app. 
I've run:
```
dependo -f cjs ./app/App.js > report.html
```
With no success: 
![image](https://cloud.githubusercontent.com/assets/2730609/8494740/a3e2d020-211c-11e5-92b9-d588aea318b2.png)

And: 
``` dependo -f cjs ./app > report.html ```

with some success: 
![image](https://cloud.githubusercontent.com/assets/2730609/8494748/bd5b02a2-211c-11e5-9a7b-fd7a9610fabf.png)

I can't tell if there is a pattern of which require() statements it is picking up on and which it isn't. It seems a bit random to me: certain require statements get picked up in some files, but don't in others. Any help debugging this would be greatly appreciated. Thanks so much!

**Comment by auchenberg** [comment]
I'm currently in the airport with limited connectivity. Can you try run https://github.com/pahen/madge and see if all your dependencies are detected? Dependo is build on top of Madge.

**Comment by tnrich** [comment]
I ran it and am getting the same results. Guess I'll ask my issue on Madge
in that case.

**Comment by auchenberg** [comment]
Yeah, it sounds like an issue in madge then. Closing it it here then.  Anyways, thanks for reporting it, and thanks for using dependo :)
