### ISSUE TITLE
No arrows?

### ISSUE THREAD

**Issue by trusktr** [auchenberg/dependo#29]
![screen shot 2016-07-05 at 9 16 18 pm](https://cloud.githubusercontent.com/assets/297678/16607432/bdafb904-42f5-11e6-9d0b-4c8d9e43eb42.png)

Why might that be? The files are like [this](https://github.com/infamous/infamous).

**Comment by trusktr** [comment]
Ah, `dependo --format es6`.

![screen shot 2016-07-05 at 9 26 07 pm](https://cloud.githubusercontent.com/assets/297678/16607589/85e9d836-42f7-11e6-83f9-40d1f185c761.png)

**Comment by trusktr** [comment]
JSS looks nice in dependo. :]

![screen shot 2016-07-05 at 9 34 34 pm](https://cloud.githubusercontent.com/assets/297678/16607643/66c9cb7c-42f8-11e6-906e-34bce581ba5d.png)

**Comment by auchenberg** [comment]
;)
