### ISSUE TITLE
Madge dependencies again

### ISSUE THREAD

**Issue by pojono** [auchenberg/dependo#37]
Hi! I have the same issue https://github.com/auchenberg/dependo/issues/15
Can you update madge dependencies again?
On my computer madge@0.5.0 not display dependency tree, and dependo not display connecctions between modules.
Latest release of Madge (3.0.0) working correctly.

**Comment by amiram** [comment]
The upgrade to 3.0.0 is not only changing dependency

**Comment by pojono** [comment]
Amiram, on your computer is everything ok? With dependo@0.2.0

**Comment by amiram** [comment]
Yes. if it is not working for you please write what is the bug exactly and how to reproduce it.

**Comment by pojono** [comment]
Okay. My OS is Ubuntu 16.04.
I download https://github.com/claymcleod/nodejs-rest-api-example and extract in home folder

For example, "app.js" has dependencies:

 var authController = require('./controllers/AuthController');
 var userController = require('./controllers/UserController');
 var recipeController = require('./controllers/RecipeController');

Then I opened my terminal and executed:
npm i -g dependo

And: 
dependo -f amd ~/nodejs-rest-api-example-master/ > ~/nodejs-rest-api-example-master/report.html

In report.html I do not see connections between modules.

![screenshot from 2018-02-01 16-45-15](https://user-images.githubusercontent.com/28717027/35681713-538637f2-076f-11e8-95e1-7f52684009d0.png)

**Comment by amiram** [comment]
I see the connections if I use `-f cjs`

**Comment by pojono** [comment]
Fine! It`s work! 

Can I exclude from graph npm modules? Like "passport" or "express".
And see only my project files dependencies? 

I used command
dependo -f cjs --exclude "^node_modules" ~/nodejs > ~/nodejs/report.html

![1](https://user-images.githubusercontent.com/28717027/35682807-07c9550c-0773-11e8-8512-c37f4e6ddbcb.JPG)

**Comment by pojono** [comment]
I exclude node_modules folder and some system dependencies

--exclude "node_modules|fs|path|http"

Working ok. Thank you very much!
